name = "miseriae"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]



[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "miseriaeentries"
id = "9887ec4c15fb41488441ec7f19ac0308"
preview_id = "todo_replace_with_preview_id"
